name: sakina_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  adhan_dart: ^1.2.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  bloc: ^9.2.0
  clipboard: ^3.0.14
  connectivity_plus: ^7.0.0
  country_flags: ^4.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_compass: ^0.8.1
  flutter_foreground_task: ^9.2.0
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  hijri: ^3.0.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  sentry_flutter: ^9.14.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  timezone: 0.10.1
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/audios/
    - assets/json/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
    - family: Uthmanic
      fonts:
      - asset: assets/fonts/kfgqpc-hafs-uthmanic-script.ttf

    - family: Amiri
      fonts:
      - asset: assets/fonts/Amiri-Bold.ttf
      - asset: assets/fonts/Amiri-Regular.ttf
      - asset: assets/fonts/Amiri-Italic.ttf
      - asset: assets/fonts/Amiri-BoldItalic.ttf     

flutter_assets:
  assets_path: assets/icons/
  output_path: lib/core/constants/app_images/app_icons.dart
  filename: app_icons.dart
  field_prefix: null

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: true
